backend:
  name: github
  repo: trkw/trkw-posts
  branch: master

media_folder: "/assets"

collections:
  - name: "post"
    label: "Posts"
    folder: "posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime"}
